### ISSUE TITLE
Indicador de puntos 

### ISSUE THREAD

**Issue by EddwardCuadra** [RenzoCanales/Nueva-Trivia#1]

**Comment by RenzoCanales** [comment]
Muchas gracias, lo tomare en cuenta:)

**Comment by pedrosc16** [comment]
Se deberia añadir cuantos puntos es lo que ha perdido o ha ganado , ya que solamente se brinda el puntaje total con la diferencia o suma ya realizada

**Comment by RenzoCanales** [comment]
Perfecto, muchas gracias por comentar y dar ideas, Había olvidado esa parte, ya pueden revisar el ultimo commit realizado, donde se le brinda solución al problema
